openapi: 3.0.3
info:
  contact:
    email: support@silohub.ag
    name: SILOHUB Support
    url: https://silohub.atlassian.net/servicedesk/customer/portals
  description: |
    Esta API contiene los datos maestros generales para SILOHUB
  license:
    name: UNLICENSED
    url: https://www.silohub.ag
  title: SILOHUB Core API
  version: 0.0.110
  x-group: API
  x-client-id: api-client-retailer
externalDocs:
  description: Confluence
  url: https://silohub.atlassian.net/wiki/spaces/SH/pages/82346030/SILOHUB+APIs
servers:
- url: https://{apiServer}
  variables:
    apiServer:
      default: api-develop.silohub.net
      description: Nombre de dominio del api server SILOHUB
      enum:
      - api-develop.silohub.net
tags:
- description: Información de países
  name: countries
- description: Información de monedas
  name: currencies
paths:
  /api/retailers/v0/{retailerCode}/currencies:
    get:
      operationId: getAllCurrencies
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Active
        in: query
        name: active
        required: false
        schema:
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCurrency'
          description: Una lista de monedas
          x-summary: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Lista todas las monedas
      tags:
      - currencies
  /api/retailers/v0/{retailerCode}/currencyConversions:
    get:
      operationId: getAllCurrencyConversions
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCurrencyConversion'
          description: Una lista de conversiones de monedas
          x-summary: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Lista todas las conversiones de monedas
      tags:
      - currencies
  /api/retailers/v0/{retailerCode}/countries:
    get:
      operationId: getAllCountries
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Active
        in: query
        name: active
        required: false
        schema:
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCountry'
          description: The response contains the list of countries
          x-summary: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Lista todos los países
      tags:
      - countries
  /api/retailers/v0/{retailerCode}/countries/{countryCode}:
    get:
      operationId: getCountryByCode
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Código ISO-3166-1 de 3 dígitos del país
        examples:
          ARG:
            value: ARG
          BRA:
            value: BRA
          USA:
            value: USA
        in: path
        name: countryCode
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              examples:
                ARG:
                  $ref: '#/components/examples/ARG'
                BRA:
                  $ref: '#/components/examples/BRA'
                USA:
                  $ref: '#/components/examples/USA'
              schema:
                $ref: '#/components/schemas/Country'
          description: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "404":
          description: Country not found
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Obtiene un país por código
      tags:
      - countries
    put:
      operationId: updateCountry
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Código ISO-3166-1 de 3 dígitos del país
        examples:
          ARG:
            value: ARG
          BRA:
            value: BRA
          USA:
            value: USA
        in: path
        name: countryCode
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/UpdateCountry'
      responses:
        "200":
          content:
            application/json:
              examples:
                ARG:
                  $ref: '#/components/examples/ARG'
                BRA:
                  $ref: '#/components/examples/BRA'
                USA:
                  $ref: '#/components/examples/USA'
              schema:
                $ref: '#/components/schemas/Country'
          description: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "404":
          description: Country not found
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Cambia los datos de un país para el retailer (referencias, notas)
      tags:
      - countries
  /api/retailers/v0/{retailerCode}/countries/{countryCode}/subdivisions:
    get:
      operationId: getAllCountrySubdivisions
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Código ISO-3166-1 de 3 dígitos del país
        examples:
          ARG:
            value: ARG
          BRA:
            value: BRA
          USA:
            value: USA
        in: path
        name: countryCode
        required: true
        schema:
          type: string
      - description: Active
        in: query
        name: active
        required: false
        schema:
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCountrySubdivision'
          description: La respuesta contiene una lista de provincias
          x-summary: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Lista todas las subdivisiones (provincias) de un país
      tags:
      - countries
  /api/retailers/v0/{retailerCode}/countries/{countryCode}/subdivisions/{countrySubdivisionCode}:
    get:
      operationId: getCountrySubdivisionByCode
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Código ISO-3166-1 de 3 dígitos del país
        examples:
          ARG:
            value: ARG
          BRA:
            value: BRA
          USA:
            value: USA
        in: path
        name: countryCode
        required: true
        schema:
          type: string
      - description: Código ISO-3166-2 de la subdivisión
        examples:
          AR-B:
            value: AR-B
          AR-X:
            value: AR-X
          BR-SC:
            value: BR-SC
        in: path
        name: countrySubdivisionCode
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              examples:
                ARG:
                  $ref: '#/components/examples/ARG'
                BRA:
                  $ref: '#/components/examples/BRA'
                USA:
                  $ref: '#/components/examples/USA'
              schema:
                $ref: '#/components/schemas/CountrySubdivision'
          description: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "404":
          description: Country not found
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Obtiene una subdivisión de un país por código
      tags:
      - countries
    put:
      operationId: updateCountrySubdivision
      parameters:
      - description: |
          El código del retailer sobre el cual se consulta la información
        examples:
          silohub:
            value: silohub
        in: path
        name: retailerCode
        required: true
        schema:
          type: string
      - description: Código ISO-3166-1 de 3 dígitos del país
        examples:
          ARG:
            value: ARG
          BRA:
            value: BRA
          USA:
            value: USA
        in: path
        name: countryCode
        required: true
        schema:
          type: string
      - description: Código ISO-3166-2 de la subdivisión
        examples:
          AR-B:
            value: AR-B
          AR-X:
            value: AR-X
          BR-SC:
            value: BR-SC
        in: path
        name: countrySubdivisionCode
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/UpdateCountrySubdivision'
      responses:
        "200":
          content:
            application/json:
              examples:
                ARG:
                  $ref: '#/components/examples/ARG'
                BRA:
                  $ref: '#/components/examples/BRA'
                USA:
                  $ref: '#/components/examples/USA'
              schema:
                $ref: '#/components/schemas/CountrySubdivision'
          description: Success
        "400":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Check parameters and try again.
          x-summary: Bad Request
        "403":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: Unable to access the resource. Check the security or permissions
          x-summary: Forbidden
        "404":
          description: Country not found
        "500":
          content:
            application/json:
              schema:
                nullable: true
                type: object
          description: This is a server side problem, check the message and logs.
          x-summary: Unexpected Error
      security:
      - OAuth2: []
      summary: Cambia los datos de un país para el retailer (referencias, notas)
      tags:
      - countries
components:
  examples:
    ARG:
      summary: ARG
      value:
        code: ARG
        name: Argentina
        numericCode: 32
        currencyCode: ARS
        active: true
    BRA:
      summary: BRA
      value:
        code: BRA
        name: Brasil
        numericCode: 76
        currencyCode: BRL
        active: true
    USA:
      summary: USA
      value:
        code: USA
        name: Estados Unidos
        numericCode: 840
        currencyCode: USD
        active: true
    UpdateARG:
      summary: ARG
      value:
        currencyCode: ARS
        active: false
    UpdateUSA:
      summary: USA
      value:
        currencyCode: USD
        active: false
  requestBodies:
    UpdateCountry:
      content:
        application/json:
          examples:
            ARG:
              $ref: '#/components/examples/UpdateARG'
            USA:
              $ref: '#/components/examples/UpdateUSA'
          schema:
            $ref: '#/components/schemas/UpdateCountry'
      description: Datos a actualizar del país
      required: true
    UpdateCountrySubdivision:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateCountrySubdivision'
      description: Información de la subdivisión del país
      required: true
  schemas:
    ArrayOfCurrency:
      description: Lista de monedas
      example:
        $ref: ../../examples/currencies/ArrayOfCurrency.yaml
      items:
        $ref: '#/components/schemas/Currency'
      type: array
    ArrayOfCurrencyConversion:
      description: Lista de conversión de monedas
      items:
        $ref: '#/components/schemas/CurrencyConversion'
      type: array
    ArrayOfCountry:
      description: Lista de países
      example:
        $ref: ../../examples/countries/ArrayOfCountry.yaml
      items:
        $ref: '#/components/schemas/Country'
      type: array
    Country:
      description: |
        Un país definido por la ISO
      properties:
        countryCode:
          $ref: '#/components/schemas/CountryCode'
        countryAlpha3Code:
          $ref: '#/components/schemas/CountryAlpha3Code'
        countryNumericCode:
          description: Country numeric code
          type: integer
        name:
          description: Country Name
          type: string
        currencyCode:
          $ref: '#/components/schemas/CurrencyCode'
        active:
          description: Is Active
          type: boolean
        uniqueReferences:
          $ref: '#/components/schemas/UniqueReferences'
        references:
          $ref: '#/components/schemas/References'
        notes:
          $ref: '#/components/schemas/Notes'
        created:
          $ref: '#/components/schemas/AuditDate'
        updated:
          $ref: '#/components/schemas/AuditDate'
      required:
      - active
      - countryAlpha3Code
      - countryCode
      - countryNumericCode
      - created
      - currencyCode
      - name
      - updated
      type: object
    ArrayOfCountrySubdivision:
      description: Lista de provincias
      items:
        $ref: '#/components/schemas/CountrySubdivision'
      type: array
    CountrySubdivision:
      description: |
        Una provincia dentro de un país
      properties:
        countryCode:
          $ref: '#/components/schemas/CountryCode'
        countrySubdivisionCode:
          $ref: '#/components/schemas/CountrySubdivisionCode'
        name:
          description: Country Subdivision Name
          type: string
        type:
          description: Country Subdivision Type
          type: string
        parent:
          $ref: '#/components/schemas/CountrySubdivisionCode'
        active:
          description: Is Active
          type: boolean
        uniqueReferences:
          $ref: '#/components/schemas/UniqueReferences'
        references:
          $ref: '#/components/schemas/References'
        notes:
          $ref: '#/components/schemas/Notes'
        created:
          $ref: '#/components/schemas/AuditDate'
        updated:
          $ref: '#/components/schemas/AuditDate'
      required:
      - active
      - countryCode
      - countrySubdivisionCode
      - created
      - name
      - type
      - updated
      type: object
    UpdateCountry:
      properties:
        currencyCode:
          $ref: '#/components/schemas/CurrencyCode'
        active:
          description: Is Active
          type: boolean
        uniqueReferences:
          $ref: '#/components/schemas/UniqueReferences'
        references:
          $ref: '#/components/schemas/References'
      required:
      - active
      type: object
    UpdateCountrySubdivision:
      properties:
        type:
          type: string
        active:
          description: Is Active
          type: boolean
        uniqueReferences:
          $ref: '#/components/schemas/UniqueReferences'
        references:
          $ref: '#/components/schemas/References'
      required:
      - active
      - type
      type: object
    Currency:
      description: |
        Una moneda definida por la ISO
      properties:
        currencyCode:
          $ref: '#/components/schemas/CurrencyCode'
        currencyNumericCode:
          description: Currency numeric code
          type: integer
        decimals:
          description: Decimals in the currency
          type: integer
        name:
          description: Currency Name
          type: string
        active:
          description: Is Active
          type: boolean
        uniqueReferences:
          $ref: '#/components/schemas/UniqueReferences'
        references:
          $ref: '#/components/schemas/References'
        created:
          $ref: '#/components/schemas/AuditDate'
        updated:
          $ref: '#/components/schemas/AuditDate'
      required:
      - active
      - created
      - currencyCode
      - currencyNumericCode
      - decimals
      - name
      - updated
      type: object
    CurrencyConversion:
      description: |
        Una conversión de monedas
      properties:
        id:
          description: Código de la conversión
          type: string
        currencyFrom:
          $ref: '#/components/schemas/CurrencyCode'
        currencyTo:
          $ref: '#/components/schemas/CurrencyCode'
        name:
          description: Nombre de la conversión
          type: string
        active:
          description: Is Active
          type: boolean
        currentRateValue:
          description: El valor de la conversión más reciente (fecha de actualización
            <= hoy)
          format: double
          type: number
        currentRateUpdated:
          description: Fecha-Hora de la conversión más reciente
          format: date-time
          type: string
        history:
          description: Historia de los valores de la conversión
          items:
            $ref: '#/components/schemas/CurrencyConversion_history'
          type: array
        created:
          $ref: '#/components/schemas/AuditDate'
        updated:
          $ref: '#/components/schemas/AuditDate'
      required:
      - active
      - created
      - currencyFrom
      - currencyTo
      - id
      - name
      - updated
      type: object
    CountryCode:
      description: |
        Identificador de país según [ISO 3166-1 alpha-2](https://es.wikipedia.org/wiki/ISO_3166-1)
      example: '[AR, BR, CL, UY, US]'
      maxLength: 2
      minLength: 2
      type: string
    CountryAlpha3Code:
      description: |
        Identificador de país según [ISO 3166-1 alpha-3](https://es.wikipedia.org/wiki/ISO_3166-1)
      example: '[ARG, BRA, CHL, URY, USA]'
      maxLength: 3
      minLength: 3
      type: string
    CurrencyCode:
      description: '[ISO 4217 Code](https://es.wikipedia.org/wiki/ISO_4217)'
      example: '[ARS, USD, BRL, CNY]'
      maxLength: 3
      minLength: 3
      type: string
    UniqueReferences:
      description: Pares de clave-valor, que son únicas entre distintas entidades
      example:
        key1: value1
        key2: value2
      items:
        $ref: '#/components/schemas/Reference'
      type: array
    References:
      description: Pares de clave-valor, que se pueden repetir entre distintas entidades
      example:
        key1: value1
        key2: value2
      items:
        $ref: '#/components/schemas/Reference'
      type: array
    Notes:
      description: |
        Notas adicionales
      maxLength: 5000
      type: string
    AuditDate:
      description: |
        [Marca temporal](https://es.wikipedia.org/wiki/Marca_temporal) (Timestamp)
      format: date-time
      readOnly: true
      type: string
    CountrySubdivisionCode:
      description: |
        Identificador de la subdivisión del país según [ISO 3166-2](https://es.wikipedia.org/wiki/ISO_3166-2)
      example: '[AR-B, AR-C, AR-X, BR-SP, BR-SC]'
      maxLength: 7
      minLength: 4
      type: string
    Reference:
      description: |
        Referencia externa de la entidad.

        Siempre consiste en un tipo de referencia y el valor de la ella.
      properties:
        refType:
          $ref: '#/components/schemas/RefType'
        refKey:
          $ref: '#/components/schemas/RefKey'
        refValue:
          $ref: '#/components/schemas/RefValue'
      required:
      - refKey
      - refType
      - refValue
      type: object
    RefType:
      description: |
        Tipo de referencia. Por ejemplo CUIT
      example: CUIT
      pattern: ^[A-Z\-]+$
      type: string
    RefKey:
      description: |
        Clave de referencia. Por ejemplo Empresa Algoritmo
      example: ALG
      pattern: ^[A-Z\-]+$
      type: string
    RefValue:
      description: |
        Valor de la referencia. Por ejemplo el número de CUIT
      example: "30224445556"
      pattern: ^[A-Za-z0-9\-_]+$
      type: string
    CurrencyConversion_history:
      properties:
        value:
          format: double
          type: number
        date:
          description: |
            [Marca temporal](https://es.wikipedia.org/wiki/Marca_temporal) (Timestamp)
          format: date-time
          type: string
        created:
          description: |
            [Marca temporal](https://es.wikipedia.org/wiki/Marca_temporal) (Timestamp)
          format: date-time
          type: string
      type: object
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://iam-develop.silohub.net/auth/realms/SILOHUB/protocol/openid-connect/token
      type: oauth2
